spring.application.name: spring-temporal

server.port: 9191

spring.main.allow-circular-references: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus,temporalworkerinfo,scheduledtasks,shutdown
    health:
      group:
        liveness:
          include: livenessstate,cacheCheck
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  endpoint:
    shutdown:
      access: unrestricted
tracing:
  url: http://localhost:4317

temporal:
  tracing:
    jaeger:
      endpoint: http://localhost:14268/api/traces
      sampler: const # const (always), probabilistic, ratelimiting, etc.
      samplerParam: 1
